FROM alpine:3.4

MAINTAINER wuhan <wuhan@xindong.com>

ENV GOROOT=/usr/lib/go GOPATH=/go
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH

COPY . /go/src/github.com/pingcap/pd

RUN sed -i -e s'/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/' /etc/apk/repositories && \
    apk update && \
    apk add go && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /go/bin && \
    cd /go/src/github.com/pingcap/pd/ && \
    rm -rf vendor && ln -s _vendor/vendor vendor && \
    go build -o bin/pd-server cmd/pd-server/main.go && \
    cp -f ./bin/pd-server /go/bin/pd-server && \
    cp -rf ./templates /go/templates && \
    cd / && \ 
    rm -rf /go/src && \
    apk del go

EXPOSE 1234

ENTRYPOINT ["pd-server"]
